import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="trusted-types-policy" strategy="beforeInteractive">
          {`
            if (typeof window !== 'undefined' && window.trustedTypes && window.trustedTypes.createPolicy && !window.trustedTypes.defaultPolicy) {
               try {
                 window.trustedTypes.createPolicy('default', {
                   createHTML: (string) => string
                 });
               } catch (e) {
                 // Policy might already exist or be blocked
                 console.warn('Failed to create default Trusted Types policy:', e);
               }
            }
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
